import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Nunito_Sans } from 'next/font/google'
import './globals.css'
import { NextAuthProvider } from './lib/auth/nextAuthProvider'

const nunito = Nunito_Sans({ subsets: ['latin'], variable: '--font-nunito' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`${nunito.variable} bg-Mll_gray_800 font-sans text-Mll_gray_100`}
      >
        <NextAuthProvider>
          <div className="m-auto box-border max-w-6xl overflow-hidden ">
            {children}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
